name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4823e5eca174b57eded9d910df0c34113960b0e37b8c31e45b6d3944a212a2ee"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
