name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4c6f7b6684625cc3e6e5d4d2281e1e9fdfa2281d77ebc0ffecc9e3e0d856aea"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
