name = "GregTech CEu Modern Community Pack"
author = "ursamina"
version = "1.14.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb1694c06c91fb7d765c31e8ccdc177c51740b2fe89d551582a13294dc493682"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
